import type { Metadata } from "next";
import { LegalPage } from "@/components/legal-page";
import { ContactDialog } from "@/components/contact-dialog";
import { site, ogImage } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy and data handling",
  description:
    "How Servey handles your data: what we collect, what we never see, who we share it with, how long we keep it, and how to get it deleted.",
  alternates: { canonical: `${site.url}/privacy` },
  // Without an explicit og:url these inherit the homepage URL from the root
  // layout, which leaves Open Graph disagreeing with the canonical tag.
  openGraph: {
    type: "website",
    url: `${site.url}/privacy`,
    title: `Privacy Policy - ${site.name}`,
    description: "What Servey collects, what it never sees, and how to get your data deleted.",
    images: [ogImage],
  },
};

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy Policy" updated="September 2026">
      <p>
        This policy explains what Servey collects, what it deliberately never sees,
        who we share data with, how long we keep it, and how you get it removed. It
        covers both the <strong>Servey apps</strong> for macOS, iOS and iPadOS and the{" "}
        <strong>servey.in</strong> website.
      </p>
      <p>
        Servey is currently <strong>pre-launch</strong>. Until the apps are generally
        available, the only data most people give us is a waitlist email address. The
        app sections below describe the software as built, and take effect for you
        when you install it.
      </p>

      <h2>The short version</h2>
      <ul>
        <li>
          We <strong>never</strong> see your screen, your keystrokes, your files, or
          anything you type or read in the terminal.
        </li>
        <li>
          We never receive your master password, and we cannot reset it for you.
        </li>
        <li>We never sell or rent your personal data, and we never have.</li>
        <li>
          We hold your email address, your device names, your subscription status,
          and counts of how many sessions you have run. That is close to all of it.
        </li>
        <li>There is no analytics or crash-reporting SDK inside the apps at all.</li>
      </ul>

      <h2>What we collect</h2>

      <h3>Account information</h3>
      <p>
        You sign in with Google. From that we receive your{" "}
        <strong>email address</strong>, your <strong>display name</strong>, and the
        account identifier Google issues. We do not receive your Google password, and
        we do not request access to your Gmail, Drive, contacts, or calendar.
      </p>
      <p>
        Alongside that we store your <strong>country</strong> (derived from your
        device region setting), your App Store <strong>storefront</strong>, the time
        you last signed in, which platform you last used, and the app and operating
        system versions you are running. The versions exist so we can reproduce bugs
        against the right build.
      </p>

      <h3>Your devices</h3>
      <p>
        So your Mac can appear on your iPhone or iPad, we store a record for each
        device: a <strong>device identifier</strong> generated by the app, the{" "}
        <strong>device name</strong> you have given it in macOS or iOS, its type, and
        whether it is currently online. These records are scoped to your account, and
        a device you revoke is removed.
      </p>

      <h3>Connection data</h3>
      <p>
        Setting up a direct connection between two devices requires them to exchange
        network information through a server, because neither can reach the other
        until they have. That exchange contains{" "}
        <strong>candidate network addresses, including IP addresses</strong>, for both
        devices.
      </p>
      <p>
        This data is <strong>ephemeral</strong>. It exists only to introduce your two
        devices to each other, it is scoped to your account, and the record is deleted
        when the session ends. It is not used to profile you, build a location
        history, or anything else.
      </p>

      <h3>Subscription and usage</h3>
      <p>
        We store which plan you are on, whether it renews, the currency and period of
        your subscription, and the identifier your subscription was issued under. We
        also keep <strong>counts</strong>: how many screen and terminal sessions you
        have started, roughly how long they lasted in total, and how many you have
        started today. The daily count is what enforces the free tier&rsquo;s five
        sessions a day.
      </p>
      <p>
        These are numbers, not content. A count records that a session happened. It
        records nothing about what you did in it.
      </p>

      <h3>Payments</h3>
      <p>
        Subscriptions are purchased through Apple. Your card details, billing address
        and payment method go to <strong>Apple, not to us</strong> - we never see
        them, and we could not store them if we wanted to. Apple tells us that a
        subscription exists, what it covers, and when it renews or lapses.
      </p>

      <h3>The website</h3>
      <p>
        If you join the waitlist we store the <strong>email address</strong> you give
        us, along with your name, country, the time you signed up, and which part of
        the page you signed up from. If you use the contact form, we receive whatever
        you write in it.
      </p>
      <p>
        We use <strong>PostHog</strong> for website analytics, kept deliberately
        light-touch:
      </p>
      <ul>
        <li>
          We do <strong>not</strong> build a personal profile for anonymous visitors,
          and we never link analytics activity to your waitlist email address.
        </li>
        <li>
          We do <strong>not</strong> record your screen, your typing, or the contents
          of any form on this site.
        </li>
        <li>
          Your IP address is used to derive an approximate country, so we can see
          where Servey is wanted. We use it for nothing else.
        </li>
        <li>
          Analytics requests are served from <strong>servey.in</strong> rather than a
          third-party domain, so the setup does not rely on third-party cookies.
        </li>
        <li>
          If your browser sends a <strong>Do Not Track</strong> signal, we honour it
          and collect nothing at all.
        </li>
      </ul>
      <p>
        There is <strong>no analytics SDK inside the Servey apps</strong>. The
        analytics described here run on the website only.
      </p>

      <h2>What we never see</h2>
      <p>
        This section is the point of the product, so it is worth stating precisely.
      </p>
      <ul>
        <li>
          <strong>Your screen.</strong> Video travels directly between your own
          devices, encrypted end to end. We do not record it, store it, or have the
          keys to decrypt it.
        </li>
        <li>
          <strong>Your input.</strong> Mouse movement, clicks and keystrokes go to
          your Mac over the same encrypted channel. They are never logged.
        </li>
        <li>
          <strong>Your terminal.</strong> Commands you run and the output they produce
          stay between your devices and your Mac. We do not capture command history,
          output, or the contents of any file.
        </li>
        <li>
          <strong>Your master password.</strong> Your Mac stores only a key derived
          from it, in the macOS Keychain, and never transmits the password itself.
          There is deliberately no remote reset - which also means that if you forget
          it, we cannot recover it for you.
        </li>
        <li>
          <strong>Your activity log.</strong> The record your Mac keeps of connections,
          approvals, refused passwords and sessions is written to that Mac and is
          never uploaded to us.
        </li>
      </ul>
      <p>
        Some networks - strict NATs and certain mobile carriers - refuse to allow a
        direct connection between two devices. When that happens the encrypted stream
        is relayed through <strong>our own server</strong> rather than a third-party
        vendor&apos;s cloud. A relay forwards encrypted packets; it does not decrypt
        them, and we do not record their contents.
      </p>

      <h2>How we use it</h2>
      <ul>
        <li>To sign you in and pair your devices to your own account.</li>
        <li>
          To introduce your devices to each other so a direct connection can be made.
        </li>
        <li>
          To determine what your plan includes and to enforce free-tier limits.
        </li>
        <li>
          To diagnose faults, understand which builds and OS versions are affected,
          and keep the service running.
        </li>
        <li>
          To detect and prevent abuse, fraud, and attempts to access an account that
          is not yours.
        </li>
        <li>To contact you about your account, and about launch if you asked us to.</li>
      </ul>
      <p>
        We do not use your data for advertising, we do not build advertising profiles,
        and we do not use it to train machine-learning models.
      </p>

      <h2>Who we share it with</h2>
      <p>
        We do <strong>not sell or rent</strong> your personal data. We share the
        minimum necessary with service providers who process it on our behalf:
      </p>
      <ul>
        <li>
          <strong>Google Firebase</strong> - authentication, and the database holding
          your device and signaling records.
        </li>
        <li>
          <strong>Supabase</strong> - the database holding account, subscription and
          usage records.
        </li>
        <li>
          <strong>Apple</strong> - purchases, subscription status and renewals.
        </li>
        <li>
          <strong>Resend</strong> - delivers waitlist and account email on our behalf,
          and processes your name and email address for that purpose only.
        </li>
        <li>
          <strong>PostHog</strong> - website analytics, as described above.
        </li>
      </ul>
      <p>
        We may also disclose data where we are legally required to, or to establish or
        defend a legal claim. If Servey is ever acquired or merged, your data may
        transfer as part of that business, and this policy would continue to apply
        until you are told otherwise.
      </p>

      <h2>How long we keep it</h2>
      <ul>
        <li>
          <strong>Connection records</strong> - deleted when the session ends.
        </li>
        <li>
          <strong>Device records</strong> - kept until you revoke the device or delete
          your account.
        </li>
        <li>
          <strong>Account, subscription and usage records</strong> - kept while your
          account exists, and after closure only for as long as we need them for tax,
          accounting and legal obligations.
        </li>
        <li>
          <strong>Waitlist email</strong> - kept until you unsubscribe or ask us to
          remove it.
        </li>
        <li>
          <strong>Your activity log</strong> - stored on your Mac, capped at the most
          recent entries, and removable by you at any time. We never hold a copy.
        </li>
      </ul>

      <h2>Your rights</h2>
      <p>
        Wherever you live, you can ask us to give you a copy of the personal data we
        hold about you, correct it if it is wrong, delete it, or stop using it for a
        particular purpose. You can withdraw consent at any time, and you can ask us
        not to send you email.
      </p>
      <p>
        If you are in India, these rights are given to you by the{" "}
        <strong>Digital Personal Data Protection Act, 2023</strong>. If you are in the
        UK, the EU or the EEA, they are given to you by the{" "}
        <strong>UK GDPR and the GDPR</strong>, and you also have the right to complain
        to your local supervisory authority.
      </p>
      <p>
        <strong>To delete your account and data</strong>, email{" "}
        <a href={`mailto:${site.email}`}>{site.email}</a> from the address you signed
        up with. We will confirm the request, delete your account record, device
        records, usage counts and waitlist entry, and tell you when it is done. We aim
        to complete requests within <strong>30 days</strong>, and to resolve any
        complaint within <strong>90 days</strong>. Deleting your Servey account does
        not cancel a subscription bought through Apple - manage that in your Apple
        account settings.
      </p>

      <h2>Security</h2>
      <p>
        Your screen and input are encrypted end to end between your own devices.
        Access to your records is enforced at the database level, scoped to your
        authenticated account, so one account cannot read another&apos;s. Your master
        password never leaves your Mac in a recoverable form. Payment details never
        reach us at all.
      </p>
      <p>
        No system is perfectly secure, and we will not claim otherwise. If a breach
        affects your personal data we will notify you and the relevant authority as
        required by law.
      </p>

      <h2>Children</h2>
      <p>
        Servey is not directed at children. You must be at least{" "}
        <strong>13 years old</strong> to use it, and old enough to agree to this
        policy where you live. If we learn we have collected data from a child below
        that age, we will delete it.
      </p>

      <h2>Where your data is processed</h2>
      <p>
        Servey is operated from <strong>India</strong>. Our service providers operate
        globally, so your data may be processed on servers outside your country,
        including in the United States and the European Union. Where the law requires
        a safeguard for that transfer, we rely on the standard contractual protections
        our providers offer.
      </p>

      <h2>Ownership, availability and discontinuation</h2>
      <p>
        Servey - the applications, the website, the name, the design, and all
        associated intellectual property - is owned by{" "}
        <strong>the builders of Servey</strong> and its rights holders. Nothing in
        this policy, and nothing in your use of the service, transfers any ownership
        in it to you. Your subscription grants you a personal, non-transferable right
        to use the apps while it is active, and no more.
      </p>
      <p>
        Content that is yours stays yours. Your files, your terminal sessions and
        whatever is on your Mac belong to you, and we claim no rights over any of it.
      </p>
      <p>
        We may change, suspend, limit or <strong>discontinue</strong> Servey, any part
        of it, or support for it, at our discretion - including where continuing would
        not be sustainable for the organisation, or where it is necessary for the
        welfare, viability or security of Servey and the people who build it. Where a
        discontinuation is planned rather than forced on us, we will give reasonable
        notice, stop billing, and give you the chance to export or delete your data
        before access ends. If the service stops permanently, we will delete personal
        data we no longer have a legal reason to keep.
      </p>
      <p>
        Your terminal sessions are ordinary tmux sessions on your own Mac, and the app
        shows you the command to attach to them. That is deliberate: if Servey ever
        goes away, the work you started does not go with it.
      </p>

      <h2>Changes to this policy</h2>
      <p>
        We will update this page as Servey changes, and the date at the top always
        reflects the current version. If a change materially affects how we handle
        your data, we will tell you by email or in the app before it takes effect
        rather than relying on you to notice.
      </p>

      <h2>Contact</h2>
      <p>
        For any privacy question, to exercise any right above, or to raise a
        grievance, email <a href={`mailto:${site.email}`}>{site.email}</a> and mark it
        for the attention of our Grievance Officer. You can also reach us through the{" "}
        <ContactDialog>
          <button type="button" className="text-accent-strong underline underline-offset-2">
            contact form
          </button>
        </ContactDialog>{" "}
        on this website. We answer privacy mail ourselves, and we aim to reply within
        a few working days.
      </p>
    </LegalPage>
  );
}
